/**
 * Bundles the pure model layer (types + domain + model) into one classic
 * browser script with zero imports, so dist/index.html stays dependency-free.
 *
 * Uses the TypeScript compiler API only as a transpiler: each file is stripped
 * to JS, internal imports are dropped (everything lands in one scope), and the
 * public surface is pinned on globalThis.EtfLab. Nothing here executes the
 * model; it only packages it.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const OUT = join(ROOT, 'web', 'vendor', 'model.bundle.js');

const SOURCES = [
  'src/types.ts',
  'src/domain/tax.ts',
  'src/domain/ipo.ts',
  'src/domain/portfolio.ts',
  'src/model.ts',
];

const EXPORTS = [
  'compute',
  'computeIpo',
  'tradingCostPct',
  'ipoSample',
  'buildPortfolio',
  'exchangeSplit',
  'namesToReachWeight',
  'ticketsFromMarketValue',
  'expectedWins',
  'expectedWinsDetailed',
  'profitPerWin',
  'expectedProfit',
  'winningRate',
  'effectiveDividendTaxRate',
  'personalLongTermRate',
  'impliedTaxRate',
  'METHOD_LABELS',
  'ALL_METHODS',
  'MARKET_VALUE_PER_TICKET',
  'TAX_BANDS',
  'ETF_TAX_BOUNDS',
  'ASSUMPTIONS',
];

function transpile(path: string, source: string): string {
  const out = ts.transpileModule(source, {
    compilerOptions: {
      module: ts.ModuleKind.ESNext,
      target: ts.ScriptTarget.ES2020,
    },
    fileName: path,
  });
  return out.outputText;
}

/** Drop internal module wiring so files can share one scope. */
function delocalize(js: string): string {
  return js
    .split('\n')
    .filter((line) => {
      const t = line.trim();
      if (t.startsWith('import ')) return false;
      if (t.startsWith('export type ') || t.startsWith('export {')) return false;
      return true;
    })
    .map((line) => line.replace(/^(\s*)export (default )?/, '$1'))
    .join('\n');
}

async function main(): Promise<void> {
  const parts: string[] = [];
  for (const rel of SOURCES) {
    const source = await readFile(join(ROOT, rel), 'utf8');
    parts.push(`// ---- ${rel} ----\n${delocalize(transpile(rel, source))}`);
  }

  const bundle = [
    '"use strict";',
    '// Generated by src/cli/bundle-model.ts. Do not edit by hand.',
    ...parts,
    `globalThis.EtfLab = { ${EXPORTS.join(', ')} };`,
    '',
  ].join('\n');

  await mkdir(dirname(OUT), { recursive: true });
  await writeFile(OUT, bundle, 'utf8');
  console.log(`wrote web/vendor/model.bundle.js (${(bundle.length / 1024).toFixed(1)} KB)`);

  // Smoke check: the bundle must parse as a classic script.
  const { execFile } = await import('node:child_process');
  await new Promise<void>((resolve, reject) => {
    execFile(process.execPath, ['--check', OUT], (err) => (err ? reject(err) : resolve()));
  });
  console.log('bundle parses cleanly');
}

await main();
